version: '3'

services:
  app-xyz:
    build: .
    restart: always
    ports:
      - "8080:80"
    container_name: app-xyz
    image: app-xyz
    environment:
      - JWT_ACCESS_SECRET=supersecretrandomstring2019283
      - JWT_REFRESH_SECRET=supersecretrandomstring2912739
      - PORT=80
      - DB_HOST=mysql-xyz
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_NAME=XYZ_multi_finance
      - DB_PASSWORD=secretrootpassword
  
  mysql-xyz:
    build: ./database
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretrootpassword
      - MYSQL_DATABASE=XYZ_multi_finance
      - MYSQL_USER=xyz_user
      - MYSQL_PASSWORD=xyzpassworduser
    volumes:
      - ./database/data:/var/lib/mysql
    container_name: mysql-xyz
    image: mysql-xyz