package const_value

const (
	DATE_FORMAT_WITH_TIME    = "2006-01-02 15:04:05"
	DATE_FORMAT              = "2006-01-02"
	STATUS_PENAGIHAN_UNPAID  = "UNPAID"
	STATUS_PENAGIHAN_PAID    = "PAID"
	STATUS_PEMINJAMAN_ACTIVE = "ACTIVE"
	STATUS_PEMINJAMAN_LUNAS  = "PAID"
)
